rvm:
  - 1.8.7
  - 1.9.3
notifications:
  email:
    - <your email address>
env:
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.2
